✨ Add: state reset when clicking Prev/Next buttons
poap-xyz/poap-gallery pull request #50
Opened 2022-01-16 17:21 UTC by sebasfavaron

## Summary

Error this fixes:
- when clicking Next/Prev from an event without tokens to an event with tokens, the latter wouldn't load

This was because before the navigation improvement the Next/Prev buttons reloaded the page, but now the component remained the same so some cleanup before clicking the buttons was needed

## Type of change

- [X] Bug fix (non-breaking change which fixes an issue)
- [ ] New feature (non-breaking change which adds functionality)

## Testing

Having an event with tokens (A) and one without tokens next to it (B)
Go from an A to B clicking the Next/Prev button, then back to A and see if A's tokens are loaded correctly
A and B candidates are /event/8960 and /event/8961

## Dependencies

#45 

## Checklist:

- [X] My code follows the style guidelines of this project
- [X] I have performed a self-review of my own code
- [X] I have commented my code, particularly in hard-to-understand areas
- [ ] I have made corresponding changes to the documentation
- [X] My changes generate no new warnings
- [X] I didn't commit unnecessary logs

2022-01-17 13:53 UTC, CristianPerez06 approved these changes

2022-01-18 14:30 UTC, pablojp requested changes

2022-01-18 14:30 UTC, pablojp commented on src/pages/event.js
> +                  <Link onClick={onPageChange} to={previousEventURI}>
```suggestion
                  <Link onClick={onPageChangeHandler} to={previousEventURI}>
```

2022-01-18 14:30 UTC, pablojp commented on src/pages/event.js
> +                  <Link onClick={onPageChange} to={nextEventURI}>
```suggestion
                  <Link onClick={onPageChangeHandler} to={nextEventURI}>
```

2022-01-18 14:30 UTC, pablojp commented on src/pages/event.js
> +  const onPageChange = () => {
```suggestion
  const onPageChangeHandler = () => {
```

2022-01-18 14:33 UTC, pablojp commented on src/pages/event.js
> +                  <Link onClick={onPageChangeHandler} to={previousEventURI}>
```suggestion
                  <Link onClick={onPageChangeHandlerAAAAAAA} to={previousEventURI}>
```

2022-01-18 14:37 UTC, pablojp approved these changes

2022-01-18 14:39 UTC, merged